config/routes.rb
Rails.application.routes.draw do
  root 'home#show'

  resources :users, only: [:index, :destroy] do
    member do
      patch :make_admin
      patch :make_non_admin
    end
  end

  resources :devices, only: [:index, :new, :create, :destroy]
  resources :system_devices, only: [:index, :new, :create, :destroy]

  get '/server_status', to: 'status#status'

  get '/login',  to: 'sessions#new'
  get '/logout', to: 'sessions#destroy'

  get  '/auth/:provider/callback', to: 'sessions#create'
  post '/auth/:provider/callback', to: 'sessions#create'
  get '/tokens', to: "tokens#show"

  get '/gems/:gemname/versions/:version', to: 'versions#show', as: :gem_version, version: /.*/

  mount Geminabox::Server, at: '/gems', as: 'geminabox'
end

app/models/device.rb
class Device < ActiveRecord::Base
  validates_presence_of :name, :user_id, :identifier, :password_digest
  validates_uniqueness_of :name, :scope => :user_id, :message => 'is already registered'

  belongs_to :user, :touch => true
  has_secure_password :validations => false

  before_validation :generate_identifier, :on => :create
  before_validation :generate_password, :on => :create

  def generate_token
    data = JSON.dump(id: id, time: Time.now.to_i)

    cipher = OpenSSL::Cipher::AES.new(256, :CBC)
    cipher.encrypt
    cipher.key = Rails.application.config.device_cipher_key
    iv = cipher.random_iv

    encrypted = cipher.update(data) + cipher.final
    CGI.escape(Base64.encode64(iv)) + ":" + CGI.escape(Base64.encode64(encrypted))
  end

  def self.find_by_token(iv, encrypted)
    decipher = OpenSSL::Cipher::AES.new(256, :CBC)
    decipher.decrypt
    decipher.key = Rails.application.config.device_cipher_key
    decipher.iv = iv

    plain = decipher.update(encrypted) + decipher.final
    hash = JSON.parse(plain)
    if Time.at(hash['time']) > Rails.application.config.token_expiration.ago
      find(hash['id'])
    else
      false
    end
  end

  def used!
    update_attribute(:used_at, Time.now)
  end

  def used?
    !!used_at
  end

  protected

  def generate_identifier
    self.identifier ||= SecureRandom.urlsafe_base64
  end

  def generate_password
    self.password ||= SecureRandom.urlsafe_base64
  end
end

app/models/uploader.rb
class Uploader < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  SYSTEM_USER_EMAIL = 'system@example.com'.freeze

  has_many :devices

  validates_presence_of :name, :email

  before_destroy :dont_destroy_last_admin
  validate :dont_lose_last_admin, :on => :update

  def system_user?
    email == SYSTEM_USER_EMAIL
  end

  def self.not_system_user
    where('email != ?', SYSTEM_USER_EMAIL)
  end

  def self.admin
    where(:is_admin => true)
  end

  def self.update_or_create_by_auth(auth_hash)
    identifier = "#{auth_hash.provider}-#{auth_hash.uid}"
    user = User.where(:external_id => identifier).first_or_initialize

    user.assign_attributes(
      :email => auth_hash.info.email,
      :name => auth_hash.info.name
    )

    if !user.system_user? && not_system_user.count == 0
      # this is the first user we are creating
      user.is_admin = true
    end

    user.save!

    user
  end

  def self.system_user
    find_or_create_by!(:external_id => 'system') do |user|
      user.name = 'System User'
      user.email = SYSTEM_USER_EMAIL
    end
  end

  def self.safe_to_remove_admin?
    User.admin.count > 1
  end

  protected

  def dont_destroy_last_admin
    if is_admin? && !self.class.safe_to_remove_admin?
      errors.add(:base, :cant_remove_last_admin)
      throw :abort
    end
  end

  def dont_lose_last_admin
    if is_admin_changed? && !is_admin? && !self.class.safe_to_remove_admin?
      errors.add(:base, :cant_remove_last_admin)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Auth
  protect_from_forgery with: :exception
  force_ssl unless Rails.env.test? || Rails.env.development? || ENV['SKIP_FORCE_SSL']
end

app/controllers/concerns/auth.rb
module Auth
  extend ActiveSupport::Concern

  included do
    before_action :authenticate!
    helper_method :current_user
  end

  protected

  def current_user
    return nil if session[:user_id].blank?
    @current_user = User.where(:id => session[:user_id]).first
  end

  def authenticate!
    redirect_to(login_path(:origin => request.path)) unless current_user
  end

  def require_admin!
    head :forbidden unless current_user.is_admin?
  end

  def logout!(msg = "You have been logged out.")
    session.delete(:user_id)
    flash[:notice] = msg
    redirect_to(login_path(:origin => request.path))
    @current_user = nil
  end
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  def index
    if current_user.devices.empty?
      @new_device = current_user.devices.new
      render :initial
    end
  end

  def new
    @new_device = current_user.devices.new
  end

  def create
    @new_device = current_user.devices.build(params.require(:device).permit(:name))

    if !@new_device.save
      render :new
    end
  end

  def destroy
    current_user.devices.find(params[:id]).destroy
    redirect_to devices_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
    if current_user.devices.empty?
      redirect_to(devices_path)
    else
      redirect_to(geminabox_path)
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authenticate!, :verify_authenticity_token

  def new
  end

  def create
    return logout!("You are not welcome here!") unless allowed_to_login

    user = User.update_or_create_by_auth(auth_hash)
    session[:user_id] = user.id
    redirect_to(request.env['omniauth.origin'] || '/')
  end

  def destroy
    logout!
  end

  protected

  def allowed_to_login
    return false unless auth_hash

    restricted_email_domain.blank? ||
      auth_hash.info.email.end_with?(restricted_email_domain)
  end

  def auth_hash
    request.env['omniauth.auth']
  end

  def restricted_email_domain
    ENV["GOOGLE_DOMAIN"]
  end
end

app/controllers/status_controller.rb
class StatusController < ActionController::Base
  protect_from_forgery with: :exception

  def status
    render text: 'ok'
  end
end

app/controllers/system_devices_controller.rb
class SystemDevicesController < ApplicationController
  before_action :require_admin!

  def index
  end

  def new
    @new_device = User.system_user.devices.new
  end

  def create
    @new_device = User.system_user.devices.build(params.require(:device).permit(:name))

    if !@new_device.save
      render :new
    end
  end

  def destroy
    User.system_user.devices.find(params[:id]).destroy
    redirect_to system_devices_path
  end
end

app/controllers/tokens_controller.rb
class TokensController < ApplicationController
  skip_before_filter :authenticate!, :verify_authenticity_token

  def show
    device = authenticate_with_http_basic{|identifier,password|
      Device.find_by_identifier(identifier).try(:authenticate, password)
    }

    render text: device.generate_token
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_admin!

  def index
    @users = User.not_system_user.order('updated_at DESC')
  end

  def make_admin
    change_is_admin(true)
  end

  def make_non_admin
    change_is_admin(false)
  end

  def destroy
    if !user.destroy
      flash[:error] = user.errors.full_messages.join('. ')
    end

    redirect_to users_path
  end

  protected

  def user
    @user ||= User.not_system_user.find(params[:id])
  end

  def change_is_admin(is_admin)
    if !user.update_attributes(:is_admin => is_admin)
      flash[:error] = user.errors.full_messages.join('. ')
    end
    redirect_to users_path
  end
end

app/controllers/versions_controller.rb
class VersionsController < ApplicationController
  helper Helpers::Geminabox
  helper_method :load_gems, :spec_for

  def show
    @version = server_instance.find_gem_by_name(params['gemname']).detect do |v|
      v.number.to_s == params['version']
    end

    unless @version
      head :not_found
      return
    end

    @spec = spec_for(@version.name, @version.number)
  end

  private

  # Allows us to use the instance methods defined in Geminabox::Server.
  #
  # We use .new! as defined by Sinatra so we get a class instance and not a
  # Sinatra::Wrapper instance.
  def server_instance
    @server_instance ||= Geminabox::Server.new!
  end

  def load_gems
    server_instance.send(:load_gems)
  end

  def spec_for(*args)
    server_instance.send(:spec_for, *args)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def omniauth_path(type)
    "/auth/#{type}?origin=#{CGI.escape(params.fetch(:origin, '/'))}"
  end
end

app/views/devices/_form.html.erb
<% @new_device.errors.full_messages.each do |msg| %>
  <p class="text-danger"><%= msg %></p>
<% end %>

<%= form_for(@new_device, :html => {:class => 'form-inline'}) do |f| %>
  <div class="form-group">
    <%= f.text_field :name, :placeholder => 'Enter the name of this computer', :class => 'form-control' %>
  </div>
  <button type="submit" class="btn btn-default">Create Token</button>
<% end %>

app/views/devices/create.html.erb
<div class="jumbotron bundler-instructions">
  <h1>Almost done!</h1>
  <p>
    You need to configure bundler to use these new credentials to access this gem server.
    These settings are stored in ~/.bundle/config. You can add the credentials by running the command below.
    <strong>We are never going to show this secret key to you again.</strong>
  </p>
  <p class="text-center">
    <code>bundle config --global <%= geminabox_url %>/ <%= @new_device.identifier %>:<%= @new_device.password %></code>
  </p>
  <p class="continue">
    <%= link_to 'Done!', devices_path, :class => 'btn btn-primary btn-lg' %>
  </p>
</div>

app/views/devices/index.html.erb
<div id="devices" class="panel panel-default">
  <div class="panel-heading">
    <h2 class="panel-title">Gem Access Tokens</h2>
  </div>

  <div class="panel-body">
    <p>
      Each computer that needs access to the gems on this server, must have its own token registered.
    </p>
  </div>

  <table class="table">
    <% current_user.devices.each do |device| %>
      <tr>
        <td class="name"><%= device.name %></td>
        <td class="last-used">
          <% if device.used? %>
            used <%= time_ago_in_words(device.used_at) %> ago
          <% else %>
            never used
          <% end %>
        </td>
        <td class="action">
          <%= link_to 'Delete', device_path(device), :class => 'text-danger pull-right', :data => {:method => 'delete', :confirm => 'Really?'} %>
        </td>
      </tr>
    <% end %>
    <tr class="new">
      <td colspan="3">
        <%= link_to icon('plus', 'Register a new computer'), new_device_path %>
      </td>
    </tr>
  </table>
</div>

app/views/devices/initial.html.erb
<div class="jumbotron">
  <h1>Welcome <%= current_user.name %>!</h1>
  <p>
    In order to use the the gems on this server you need to create a token for each of your computers.

    <%= render 'form' %>
  </p>
</div>

app/views/devices/new.html.erb
<div class="jumbotron">
  <h1>Alright...</h1>
  <p>
    Let's get you setup on this computer.

    <%= render 'form' %>
  </p>
</div>

app/views/gems/_gem_dependency.erb
<li>
  <%= link_to_gem(gem_dependency.name) %>
  <%= gem_dependency.requirement %>
</li>

app/views/gems/_version_details.erb
<div class="row">
  <div class="col-md-4">
    <h4>Runtime Dependencies</h4>
    <ul class="list-unstyled">
      <%= partial_collection(:gem_dependency, spec.runtime_dependencies) %>
    </ul>
  </div>
  <div class="col-md-4">
    <h4>Development Dependencies</h4>
    <ul class="list-unstyled">
      <%= partial_collection(:gem_dependency, spec.development_dependencies) %>
    </ul>
  </div>
  <div class="col-md-4">
    <h4>Dependents</h4>
    <ul class="list-unstyled">
      <%= partial_collection(:gem_dependency, reverse_dependencies(version)) %>
    </ul>
  </div>
</div>

<%= link_to 'Delete', "#{geminabox_path}/gems/#{version.gemfile_name}.gem", class: 'btn btn-danger', data: {confirm: 'Really?'}, method: :delete %>

app/views/gems/gem.erb
<% @gem.by_name do |name, versions| %>
  <% latest_spec = spec_for(name, versions.newest.number) %>
  <% versions_array = versions.to_a.reverse %>
  <% recent_versions = versions_array.slice!(0, RECENT_GEM_VERSIONS_TO_SHOW) %>
  <div class="page-header">
    <h1>
      <%= name %>
      <small><%= latest_spec.summary %></small>
      <span class="label label-primary pull-right"><%= versions.newest.number %></span>
    </h1>
    <p class="lead"><%= latest_spec.description %></p>
  </div>

  <div class="panel-group" id="versions">
    <% recent_versions.each do |version| %>
      <% spec = spec_for(version.name, version.number) %>
      <% number_class = version.number.to_s.tr('.', '_') %>

      <div class="panel panel-default">
        <div class="panel-heading">
          <h4 class="panel-title">
            <a data-toggle="collapse" data-parent="#versions" href="#version-<%= number_class %>">
              <strong><%= version.name %></strong>
              <%= version.number %>
              <% if uploader = Uploader.where(gem_name: spec.name, gem_version: spec.version.to_s).first %>
                Uploaded by <%= uploader.user.try(:email) %>
              <% end %>
              <span class="pull-right"><%= spec.date.to_date %></span>
            </a>
          </h4>
        </div>
        <div id="version-<%= number_class %>" class="panel-collapse collapse <%= version == versions.newest ? 'in' : '' %>">
          <div class="panel-body">
            <%= erb :_version_details, {}, spec: spec, version: version %>
          </div>
        </div>
      </div>
    <% end %>

    <% versions_array.each do |version| %>
      <div class="panel panel-default">
        <div class="panel-heading">
          <a href="<%= gem_version_path(gemname: name, version: version.number) %>">
            <h4 class="panel-title">
              <strong><%= version.name %></strong>
              <%= version.number %>
            </h4>
          </a>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/gems/index.erb
<h1>Gems</h1>

<% if @gems.any? %>
  <table class="table">
    <thead>
      <th>Name</th>
      <th>Author</th>
      <th>Versions</th>
    </thead>
    <tbody>
    <% @gems.by_name do |name, versions| %>
      <tr>
        <td><a href="<%= url("/gems/#{name}") %>"><%= name %></a></td>
        <td>
          <% if spec = spec_for(name, versions.newest.number) %>
            <%= spec.authors.zip(Array(spec.email)).map do |author, email|
              link_to_author(author, email, spec.homepage)
            end.join(', ') %>
          <% end %>
        </td>
        <td class="versions">
          <%= versions.each.reverse_each.first(5).map do |version|
            "<a class='version' href='#{ url("/gems/#{name}#version-#{version.number.to_s.gsub '.', '_'}") }'>#{version.number}</a>"
          end.join(', ') %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% else %>
  <p>No gems have been added to the server yet.</p>
<% end %>

app/views/gems/layout.erb
../layouts/application.html.erb

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Private Ruby Gems</title>

    <%= stylesheet_link_tag 'application', :media => 'all' %>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="container">
      <div class="navbar navbar-default" role="navigation">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">Private Ruby Gems</a>
          </div>
          <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <li><a href="/gems">Gems</a></li>
            </ul>

            <% if current_user && current_user.is_admin? %>
              <ul class="nav navbar-nav">

                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">System <span class="caret"></span></a>
                  <ul class="dropdown-menu" role="menu">
                    <li><%= link_to 'System Access Tokens', '/system_devices' %></li>
                    <li><%= link_to 'Users', '/users' %></li>
                  </ul>
                </li>
              </ul>
            <% end %>

            <% if revision = Rails.application.config.revision %>
              <ul class="nav navbar-nav">
                <li><a href="https://github.com/zendesk/geminastrongbox/commit/<%= revision %>">Version <%= revision[0...7] %></a></li>
              </ul>
            <% end %>

            <% if current_user %>
              <ul class="nav navbar-nav navbar-right">
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.name %> <span class="caret"></span></a>
                  <ul class="dropdown-menu" role="menu">
                    <li><%= link_to 'Access Tokens', '/devices' %></li>
                    <li><%= link_to 'Logout', '/logout' %></li>
                  </ul>
                </li>
              </ul>
            <% end %>
          </div>
        </div>
      </div>

      <% if flash[:error] %>
        <div class="alert alert-danger" role="alert"><%= flash[:error] %></div>
      <% end %>
      <% if flash[:notice] %>
        <div class="alert alert-info" role="alert"><%= flash[:notice] %></div>
      <% end %>

      <%= yield %>
    </div>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/system_devices/create.html.erb
<div class="jumbotron bundler-instructions">
  <h1>Almost done!</h1>
  <p>
    You need to configure bundler (>= 1.6.5) to use these new credentials to access this gem server.
    These settings are stored in ~/.bundler/config. You can add the credentials to by running the command below.
    <strong>We are never going to show this secret key to you again.</strong>
  </p>
  <p class="text-center">
    <code>bundle config --global <%= geminabox_url %>/ <%= @new_device.identifier %>:<%= @new_device.password %></code>
  </p>
  <p class="continue">
    <%= link_to 'Done!', system_devices_path, :class => 'btn btn-primary btn-lg' %>
  </p>
</div>

app/views/system_devices/index.html.erb
<div id="devices" class="panel panel-default">
  <div class="panel-heading">
    <h2 class="panel-title">Gem Access System Tokens</h2>
  </div>

  <div class="panel-body">
    <p>
      These represent external systems that need access to your gems like CI systems and production servers.
    </p>
  </div>

  <table class="table">
    <% User.system_user.devices.each do |device| %>
      <tr>
        <td class="name"><%= device.name %></td>
        <td class="last-used">
          <% if device.used? %>
            used <%= time_ago_in_words(device.used_at) %> ago
          <% else %>
            never used
          <% end %>
        </td>
        <td class="action">
          <%= link_to 'Delete', system_device_path(device), :class => 'text-danger pull-right', :data => {:method => 'delete', :confirm => 'Really?'} %>
        </td>
      </tr>
    <% end %>
    <tr class="new">
      <td colspan="3">
        <%= link_to icon('plus', 'Register a system token'), new_system_device_path %>
      </td>
    </tr>
  </table>
</div>

app/views/system_devices/new.html.erb
<div class="jumbotron">
  <h1>New System Token</h1>
  <p>
    We just need to get the name of the system that you want to give access to your gems.

    <% @new_device.errors.full_messages.each do |msg| %>
      <p class="text-danger"><%= msg %></p>
    <% end %>

    <%= form_for(@new_device, :url => system_devices_path, :html => {:class => 'form-inline'}) do |f| %>
      <div class="form-group">
        <%= f.text_field :name, :placeholder => 'Enter the name of the system', :class => 'form-control' %>
      </div>
      <button type="submit" class="btn btn-default">Create System Token</button>
    <% end %>
  </p>
</div>

app/views/users/edit.html.erb
<div id="user" class="well well-lg center-block">
  <h1><%= @user.name %></h1>

  <%= form_for @user do |f| %>
    <div class="form-group">
      <label>Name</label>
      <p class="form-control-static"><%= @user.name %></p>
    </div>

    <div class="form-group">
      <label>Email</label>
      <p class="form-control-static"><%= @user.email %></p>
    </div>

    <div class="checkbox">
      <label>
        <%= f.check_box :is_admin %> Is Admin?
      </label>
    </div>

    <%= f.submit 'Update', :class =>'btn btn-primary' %>
  <% end %>
</div>

app/views/users/index.html.erb
<h1>Users <small>ordered by last activity</small></h1>
<table id="users" class="table table-striped table-hover">
  <thead>
    <th>Name</th>
    <th>Email</th>
    <th>Admin</th>
    <th>Last Activity</th>
    <th></th>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td class="name"><%= user.name %></td>
        <td class="email"><%= user.email %></td>
        <td class="is-admin">
          <% if !user.system_user? %>
            <% if user.is_admin? %>
              <%= link_to icon('check-square-o'), make_non_admin_user_path(user), :data => {:method => :patch} %>
            <% else %>
              <%= link_to icon('square-o'), make_admin_user_path(user), :data => {:method => :patch} %>
            <% end %>
          <% end %>
        </td>
        <td class="last-activity"><%= user.updated_at %></td>
        <td class="action"><%= link_to 'delete', user_path(user), :data => {:method => :delete} %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/versions/show.html.erb
<div class="page-header">
  <h1>
    <%= @version.name %>
    <small><%= @spec.summary %></small>
    <span class="label label-primary pull-right"><%= @version.number %></span>
  </h1>
  <p class="lead"><%= @spec.description %></p>
  <p>
    <% if uploader = Uploader.find_by(gem_name: @spec.name, gem_version: @spec.version.to_s) %>
      Uploaded by <%= uploader.user.try(:email) %> at <%= uploader.created_at.to_s(:db) %> UTC
    <% end %>
  </p>
</div>

<%= render 'gems/version_details', version: @version, spec: @spec %>